<a href="https://colab.research.google.com/github/priyansh4320/tensorflow-practice/blob/main/SNS_MODEL_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semantic Similarity Classification Model

In [ ]:
#installing necessary lib
!pip install transformers
!pip install sentence-transformers

In [ ]:
!pip install torch torchvision -U

In [ ]:
#checking if torch is present
import torch

print(torch.__version__)

2.0.1+cu118


In [ ]:
#import necessary lib
from sentence_transformers import SentenceTransformer, util
import numpy as np
from functools import cache

In [ ]:
# load pretrained model stsb-roberta-large
# will be used to extract embeddings and Similarity score from text
model = SentenceTransformer('stsb-roberta-large')

In [ ]:
#testing the pretrained model
sentence1 = "I like Python because I can build AI applications"
sentence2 = "I like Python because I can do data analytics"
# encode sentences to get their embeddings
embedding1 = model.encode(sentence1, convert_to_tensor=True)
embedding2 = model.encode(sentence2, convert_to_tensor=True)
# compute similarity scores of two embeddings
cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
print("Sentence 1:", sentence1)
print("Sentence 2:", sentence2)
print("Similarity score:", cosine_scores.item())

Sentence 1: I like Python because I can build AI applications
Sentence 2: I like Python because I can do data analytics
Similarity score: 0.8015277981758118


In [ ]:
e = model.encode(df['text1'][0:5],convert_to_tensor=True)

In [ ]:
#import dataset
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Precily AI/Precily_Text_Similarity.csv")
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  
0  gardener wins double in glasgow britain s jaso...  
1  amnesty chief laments war failure the lack of ...  
2  hanks greeted at wintry premiere hollywood sta...  
3  redford s vision of sundance despite sporting ...  
4  mauresmo opens with victory in la amelie maure...

In [ ]:
#function for computing similarity score for each pair of text
@cache
def compute_similarity_score(dataframe , len_of_dataframe):
  # encode sentences to get their embeddings
  embedding1 = model.encode(sentence1, convert_to_tensor=True)
  embedding2 = model.encode(sentence2, convert_to_tensor=True)
# compute similarity scores of two embeddings
  cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
  return cosine_scores.item()

score = compute_similarity_score(sentence1,sentence2)
score

[0.25230738520622253,
 0.2531975209712982,
 0.1261926293373108,
 0.34469395875930786,
 0.38908863067626953,
 0.1271783858537674,
 0.11437475681304932,
 0.2231573760509491,
 0.1401197612285614,
 0.2657514214515686]

In [ ]:
#compute similarity score for every pair
similarity_scores = []
for i in range(len(df)):
  similarity_scores.append(compute_similarity_score(df['text1'][i],df['text2'][i]))

similarity_score[:10]

[0.25230738520622253,
 0.2531975209712982,
 0.1261926293373108,
 0.34469395875930786,
 0.38908863067626953,
 0.1271783858537674,
 0.11437475681304932,
 0.2231573760509491,
 0.1401197612285614,
 0.2657514214515686]

In [ ]:
len(similarity_scores)

3000

In [ ]:
#Generating labels for training 1: similar , 0: not similar
result = []
for i in similarity_scores:
  if i>0.5:
    result.append(1)
  else:
    result.append(0)

In [ ]:
len(result)

list

In [ ]:
#append result and similarity to dataset
df['similarity'] = similarity_scores
df['result']     = result
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  similarity  result  
0  gardener wins double in glasgow britain s jaso...    0.252307       0  
1  amnesty chief laments war failure the lack of ...    0.253198       0  
2  hanks greeted at wintry premiere hollywood sta...    0.126193       0  
3  redford s vision of sundance despite sporting ...    0.344694       0  
4  mauresmo opens with victory in la amelie maure...    0.389089       0

In [ ]:
#save progress
df.to_csv("text_similarity2.csv")

In [ ]:
#load progess
df = pd.read_csv("/content/drive/MyDrive/Precily AI/text_similarity2.csv")
df= df[['text1','text2','similarity','result']]
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  similarity  result  
0  gardener wins double in glasgow britain s jaso...    0.252307       0  
1  amnesty chief laments war failure the lack of ...    0.253198       0  
2  hanks greeted at wintry premiere hollywood sta...    0.126193       0  
3  redford s vision of sundance despite sporting ...    0.344694       0  
4  mauresmo opens with victory in la amelie maure...    0.389089       0

In [ ]:
#now extract embeddings
text1_embedding, text2_embedding = [],[]
df_len = len(df)

In [ ]:

embedding1 = model.encode(df['text1'], convert_to_tensor=True)
embedding2 = model.encode(df['text2'], convert_to_tensor=True)


In [ ]:
embedding1[:5]

tensor([[ 0.5764,  0.6705,  0.7088,  ...,  0.8344, -0.5563, -0.2122],
        [-0.6163,  0.8100,  0.1974,  ...,  0.3304, -0.8882, -0.1140],
        [ 0.4100,  1.0177,  0.4061,  ...,  0.3243, -0.4040, -0.3931],
        [-0.6264,  0.1350, -0.1653,  ...,  0.1603, -1.2940,  0.0064],
        [ 0.4911, -0.1716,  0.9481,  ...,  0.1972, -0.5469,  0.5312]])

In [64]:
#now concatinate embedding1 and embedding2 for training as X numpy array
X = np.concatenate([embedding1,embedding2],axis=1)
X[:5]

array([[ 0.5763947 ,  0.670536  ,  0.70880157, ...,  1.1659852 ,
        -0.5401187 , -0.06296479],
       [-0.6163493 ,  0.81004924,  0.19742069, ..., -0.45929876,
        -1.0696709 ,  0.01065269],
       [ 0.41002226,  1.0177351 ,  0.4061116 , ..., -0.17751054,
        -2.8012593 ,  0.8040323 ],
       [-0.62638664,  0.13501613, -0.16530176, ...,  0.6684279 ,
        -1.9837092 ,  0.34543216],
       [ 0.4911102 , -0.1716211 ,  0.94814175, ...,  0.35773   ,
        -0.55295336,  0.77124536]], dtype=float32)

In [65]:
# target variable
Y = np.asarray(df['similarity'])
Y[:5]

array([0.25230739, 0.25319752, 0.12619263, 0.34469396, 0.38908863])

In [66]:
#import tensorflow lib for modelling
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
#from tensorflow.keras.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split


In [67]:
#splitting the dataset
trainx , testx, trainy, testy = train_test_split(X,Y,test_size=0.2);

In [68]:
#calculating max_length of sequences in to pass it as parameter in Dense layer: input_dim
seq_len = [len(i) for i in X ]
max_sequence_length = max(seq_len)

In [69]:

#tensorflow regression model: train-test
mod = Sequential()
mod.add(Dense(64, input_dim= max_sequence_length, activation = 'relu' ))
mod.add(Dense(32,activation='relu'))
mod.add(Dense(1))
mod.compile(loss='mse',metrics = [tf.keras.metrics.MeanAbsolutePercentageError()], optimizer='adam')
mod.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 64)                131136    
                                                                 
 dense_5 (Dense)             (None, 32)                2080      
                                                                 
 dense_6 (Dense)             (None, 1)                 33        
                                                                 
Total params: 133,249
Trainable params: 133,249
Non-trainable params: 0
_________________________________________________________________


In [72]:
mod.fit(trainx,trainy, epochs = 10)

Epoch 1/10
75/75 [==============================] - 0s 5ms/step - loss: 0.0092 - mean_absolute_percentage_error: 49.4257
Epoch 2/10
75/75 [==============================] - 1s 7ms/step - loss: 0.0083 - mean_absolute_percentage_error: 47.6134
Epoch 3/10
75/75 [==============================] - 1s 7ms/step - loss: 0.0074 - mean_absolute_percentage_error: 43.6260
Epoch 4/10
75/75 [==============================] - 1s 7ms/step - loss: 0.0069 - mean_absolute_percentage_error: 42.0272
Epoch 5/10
75/75 [==============================] - 0s 6ms/step - loss: 0.0062 - mean_absolute_percentage_error: 38.2615
Epoch 6/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0056 - mean_absolute_percentage_error: 36.9552
Epoch 7/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0051 - mean_absolute_percentage_error: 34.7353
Epoch 8/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0045 - mean_absolute_percentage_error: 32.2561
Epoch 9/10
75/75 [==============

In [73]:
#predict test set
pred2 = mod.predict(testx)
for i in range(20):
  tf.print(pred2[i])

19/19 [==============================] - 0s 2ms/step
array([0.32455617], dtype=float32)
array([0.30322438], dtype=float32)
array([0.32246876], dtype=float32)
array([0.24892825], dtype=float32)
array([0.36504853], dtype=float32)
array([0.2532853], dtype=float32)
array([0.16973442], dtype=float32)
array([0.22577855], dtype=float32)
array([0.34926116], dtype=float32)
array([0.22099927], dtype=float32)
array([0.29183432], dtype=float32)
array([0.18547797], dtype=float32)
array([0.47035998], dtype=float32)
array([0.25229773], dtype=float32)
array([0.16408649], dtype=float32)
array([0.1626867], dtype=float32)
array([0.3051672], dtype=float32)
array([0.38683876], dtype=float32)
array([0.2852015], dtype=float32)
array([0.36553773], dtype=float32)


In [74]:
testy[:20]

array([0.20997454, 0.05233978, 0.39584315, 0.2755419 , 0.12888476,
       0.28943291, 0.2474981 , 0.21724859, 0.33003709, 0.37265736,
       0.28910118, 0.19156843, 0.36917993, 0.25380418, 0.22002032,
       0.37628984, 0.41672543, 0.39234945, 0.46911845, 0.26794887])

In [76]:
#evaluate model
mod.evaluate(testx,testy)
#eval shows mse as large but if i extract labels 1(similar) and  0(not similar) we get:

19/19 [==============================] - 0s 3ms/step - loss: 0.0199 - mean_absolute_percentage_error: 217.2517


[0.019897891208529472, 217.25173950195312]

In [86]:
pred_label,test_label = [] ,[]
for i in range(20):
  if pred2[i]>.5:
    pred_label.append(1)
  else:
    pred_label.append(0)

  if testy[i]>.5:
    test_label.append(1)
  else:
    test_label.append(0)

print(pred_label,test_label)

#as you can see after extracting labels we have highly accurate regression model

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [83]:
#tensorflow regression model all data
model = Sequential()
model.add(Dense(64, input_dim= max_sequence_length, activation = 'relu' ))
model.add(Dense(32, activation = 'relu' ))
model.add(Dense(1))

model.compile(loss='mse',metrics = [tf.keras.metrics.MeanAbsolutePercentageError()], optimizer='adam')
model.summary()
model.fit(X,Y, epochs=20)

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_21 (Dense)            (None, 64)                131136    
                                                                 
 dense_22 (Dense)            (None, 32)                2080      
                                                                 
 dense_23 (Dense)            (None, 1)                 33        
                                                                 
Total params: 133,249
Trainable params: 133,249
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
94/94 [==============================] - 2s 4ms/step - loss: 0.0442 - mean_absolute_percentage_error: 109.8922
Epoch 2/20
94/94 [==============================] - 0s 4ms/step - loss: 0.0137 - mean_absolute_percentage_error: 82.2075
Epoch 3/20
94/94 [==============================] - 0s 4ms/step - lo

In [84]:
mod.save("precily_sns_mod_complete_regression")

In [85]:
#saving the model
import shutil
from google.colab import files


folder_name = 'precily_sns_mod_complete_regression'


shutil.make_archive(folder_name, 'zip', folder_name)


files.download(f'{folder_name}.zip')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>