<a href="https://colab.research.google.com/github/priyansh4320/tensorflow-practice/blob/main/tf_hello_world.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow hello world


*   variable
*   opration


*   tensor
*   constant






In [2]:
import tensorflow as tf

In [4]:
# constants add a tf.opration to default graph and create a tensor
a = tf.constant([2],name = 'const_a')   #add tf.opration 'constant_a' to graph and create tensor named "constant_a:0"
b = tf.constant([3],name = 'const_b')   #add tf.opration 'constant_b' to graph and create tensor named "constant_b:0"

In [8]:
print("constant a: ",a,"\n","constant b: ",b)

constant a:  tf.Tensor([2], shape=(1,), dtype=int32) 
 constant b:  tf.Tensor([3], shape=(1,), dtype=int32)


In [9]:
print(a.shape,b.shape) #.shape gives shape of tensor

(1,) (1,)


In [11]:
print(a.numpy()[0]) #tensor is a numpy array with multi-dimension , so access value like this

2


# @tf.function
this let's you create a  static tensorflow function to perform tensorflow oprations


In [16]:
@tf.function
def add_ab(a,b):
  c = tf.add(a,b)
  return c

addition = add_ab(a,b) #previously defined contants
print(addition.numpy()[0]) #output is a tensor / numpy array

5


In [17]:
# we can also print addition using tf
tf.print(addition[0]) #here we don't need to call numpy() method

5




1.   scaler values : single numbers
2.   vectors       : 1D array


1.   matrix         : 2D array
2.   tensor         : multi- D array eg.3D






In [19]:
scaler = tf.constant(2, name='scaler')
vector = tf.constant([2,3,4],name="vactor")
matrix = tf.constant([[2,3,4],[2,5,6],[1,2,3]], name= "matrix")
tensor = tf.constant([[[2,3,4],[2,5,6],[1,2,3]],[[1,2,3],[3,4,5],[6,7,8]],[[1,3,2],[2,3,4],[4,5,6]]],name='tensor')

tf.print("\nscaler:", scaler)
tf.print("\nvector:", vector)
tf.print("\nmatrix:", matrix)
tf.print("\ntensor:", tensor)



scaler: 2

vector: [2 3 4]

matrix: [[2 3 4]
 [2 5 6]
 [1 2 3]]

tensor: [[[2 3 4]
  [2 5 6]
  [1 2 3]]

 [[1 2 3]
  [3 4 5]
  [6 7 8]]

 [[1 3 2]
  [2 3 4]
  [4 5 6]]]


In [20]:
tf.print(scaler.shape, vector.shape,matrix.shape,tensor.shape)

TensorShape([]) TensorShape([3]) TensorShape([3, 3]) TensorShape([3, 3, 3])


In [23]:
#playground

Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]]) #define two matrix

@tf.function
def mathmul(a,b):
  c = tf.matmul(a,b)
  return c

@tf.function
def add_ab(a,b):
  return tf.add(a,b)


tf.print("matrix addition: \n", add_ab(Matrix_one,Matrix_two))
tf.print("matrix multiplication: \n", mathmul(Matrix_one,Matrix_two))

matrix addition: 
 [[3 4 5]
 [4 5 6]
 [5 6 7]]
matrix multiplication: 
 [[12 12 12]
 [18 18 18]
 [24 24 24]]


# TF oprations
oprations are node that are added to the tensorflow graph

some oprations are


1.   tf.constant() : create a tensor
2.   tf.add()      : add tensors
3.   tf.subtract() : subtract tensors
4.   tf.matmul()   : perform tensor multiplication
5.   tf.divide()   : perform tensor division
6.   tf.reshape()  : reshape a tensor


In [32]:

m1 = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
m2 = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

tf.print("\nadd\n",tf.add(m1,m2))
tf.print("\nmultiply\n",tf.matmul(m1,m2))
tf.print("\nsub\n",tf.subtract(m1,m2))
tf.print("\ndivide\n",tf.divide(m1,m2))
c = tf.reshape(m1,[9])
tf.print("\nm1  :\n",m1.shape,"\nc  :\n",c,"\nc shape :\n",c.shape)


add
 [[3 4 5]
 [4 5 6]
 [5 6 7]]

multiply
 [[12 12 12]
 [18 18 18]
 [24 24 24]]

sub
 [[-1 0 1]
 [0 1 2]
 [1 2 3]]

divide
 [[0.5 1 1.5]
 [1 1.5 2]
 [1.5 2 2.5]]

m1  :
 TensorShape([3, 3]) 
c  :
 [1 2 3 ... 3 4 5] 
c shape :
 TensorShape([9])
