<a href="https://colab.research.google.com/github/priyansh4320/tensorflow-practice/blob/main/tf_linear_regression_2_easy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TF Linear Regression

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [3]:
df.shape

(17000, 9)

In [4]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [19]:
trainx = np.asarray(df[[ 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']])

trainy = np.asarray(df['median_house_value'])
trainx[:5]

array([[1.5000e+01, 5.6120e+03, 1.2830e+03, 1.0150e+03, 4.7200e+02,
        1.4936e+00],
       [1.9000e+01, 7.6500e+03, 1.9010e+03, 1.1290e+03, 4.6300e+02,
        1.8200e+00],
       [1.7000e+01, 7.2000e+02, 1.7400e+02, 3.3300e+02, 1.1700e+02,
        1.6509e+00],
       [1.4000e+01, 1.5010e+03, 3.3700e+02, 5.1500e+02, 2.2600e+02,
        3.1917e+00],
       [2.0000e+01, 1.4540e+03, 3.2600e+02, 6.2400e+02, 2.6200e+02,
        1.9250e+00]])

In [20]:
#define linear regression model

model = Sequential()

model.add(Dense(1, input_dim = len(trainx[0,:]) , activation = 'linear'))

model.compile(loss = 'mean_squared_error', optimizer = "rmsprop", metrics = [tf.keras.metrics.MeanAbsolutePercentageError() ])



In [22]:
model.fit(x= trainx , y= trainy , epochs = 1000 , verbose = 2)

Epoch 1/1000
532/532 - 1s - loss: 56286711808.0000 - mean_absolute_percentage_error: 99.6878 - 934ms/epoch - 2ms/step
Epoch 2/1000
532/532 - 1s - loss: 55152685056.0000 - mean_absolute_percentage_error: 97.9994 - 636ms/epoch - 1ms/step
Epoch 3/1000
532/532 - 1s - loss: 54033371136.0000 - mean_absolute_percentage_error: 96.3120 - 604ms/epoch - 1ms/step
Epoch 4/1000
532/532 - 1s - loss: 52948717568.0000 - mean_absolute_percentage_error: 94.6430 - 771ms/epoch - 1ms/step
Epoch 5/1000
532/532 - 1s - loss: 51886931968.0000 - mean_absolute_percentage_error: 92.9648 - 941ms/epoch - 2ms/step
Epoch 6/1000
532/532 - 1s - loss: 50836414464.0000 - mean_absolute_percentage_error: 91.2940 - 927ms/epoch - 2ms/step
Epoch 7/1000
532/532 - 1s - loss: 49815433216.0000 - mean_absolute_percentage_error: 89.6345 - 730ms/epoch - 1ms/step
Epoch 8/1000
532/532 - 1s - loss: 48811646976.0000 - mean_absolute_percentage_error: 87.9790 - 602ms/epoch - 1ms/step
Epoch 9/1000
532/532 - 1s - loss: 47837564928.0000 - mea

In [10]:
#now test model with test data
test_df = pd.read_csv("/content/sample_data/california_housing_test.csv")
test_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [21]:
testx = np.asarray(test_df[[ 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']])

testy = np.asarray(test_df['median_house_value'])
trainx[:5]

array([[1.5000e+01, 5.6120e+03, 1.2830e+03, 1.0150e+03, 4.7200e+02,
        1.4936e+00],
       [1.9000e+01, 7.6500e+03, 1.9010e+03, 1.1290e+03, 4.6300e+02,
        1.8200e+00],
       [1.7000e+01, 7.2000e+02, 1.7400e+02, 3.3300e+02, 1.1700e+02,
        1.6509e+00],
       [1.4000e+01, 1.5010e+03, 3.3700e+02, 5.1500e+02, 2.2600e+02,
        3.1917e+00],
       [2.0000e+01, 1.4540e+03, 3.2600e+02, 6.2400e+02, 2.6200e+02,
        1.9250e+00]])

In [23]:
#make prediction
pred  =  model.predict(testx)
pred[:10]

94/94 [==============================] - 0s 1ms/step


array([[195799.55 ],
       [ 96336.83 ],
       [177363.98 ],
       [ 20899.686],
       [ 71395.75 ],
       [ 69715.29 ],
       [ 73127.01 ],
       [123044.836],
       [158072.92 ],
       [143585.56 ]], dtype=float32)

In [24]:
testy[:10]

array([344700., 176500., 270500., 330000.,  81700.,  67000.,  67000.,
       166900., 194400., 164200.])